### ISSUE TITLE
Authenticate Error from Pymumble

### ISSUE THREAD

**Issue by s3m1s0n1c** [rquerk/MumbleGPT#1]
Hey Guys,

Getting the following error.. Any ideas?

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/MumbleGPT/pymumble_py3/mumble.py", line 130, in run
    if self.connect() >= PYMUMBLE_CONN_STATE_FAILED:  # some error occurred, exit here
  File "/root/MumbleGPT/pymumble_py3/mumble.py", line 190, in connect
    authenticate.client_type = self.client_type
AttributeError: 'Authenticate' object has no attribute 'client_type'```

Thanks
Sonic

**Comment by rquerk** [comment]
@s3m1s0n1c Hey sorry for not answering for so long
my best guess would be that you did not export all the necessary environment variables and/or you don't have access  to your mumble server

you need an openai access token, the password for your mumble server, a certificate for your machine to access the mumble server and the ip of the mumble server

so if you can access your server and you have all the variables then you execute python MumbleBot.py

Edit: oh and i hard coded the channel name of the mumble server... so i changed that to be an os.environ too ...
